### ISSUE TITLE
windows 自带 wsl环境中，通过docker compose 运行提示找不到 manage/getCompany, http code 502

### ISSUE THREAD

**Issue by NoComments** [zhimaAi/chatwiki#8]
![image](https://github.com/user-attachments/assets/ecdc4d82-931d-45d8-a8c1-88f69d88feef)

**Comment by hu19941107** [comment]
核心服务应该存在异常,尝试下重启:
docker compose restart chatwiki_go_core_service

**Comment by hu19941107** [comment]
重启后还是502的话,查看下错误日志:
chatwiki/internal/app/chatwiki/logs/2024/08/error/16.txt
